version: '3.6'

networks:
  app-network:
    driver: bridge
    name: app-network

services:
  ap-product-service:
    image: fucyber/laravel-lumen:latest
    container_name: ap-product-service
    restart: on-failure:5
    privileged: true
    user: root
    ports:
      - "9011:80"
    volumes:
      - ./:/var/www
      - ./dockers/nginx/logs/:/var/log/nginx
      - ./dockers/php-fpm/php7.3.ini:/etc/php7/php.ini
      - ./dockers/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
